### ISSUE TITLE
Server Booting

### ISSUE THREAD

**Issue by exception** [mkotb/MineCloud#20]
There's an issue with Server Booting some times, the ServerType decides to go null even if it is in the database, the server then dies and starts again in an infinite loop. Refer to @Sigurs for more information on this issue.

**Comment by Sigurs** [comment]
It seems like (from looking at the database) that the port is set first from -1 to something.
Next the ramUsage is set from -1 to something and it seems like simultaneously the port is changed back to -1.

**Comment by mkotb** [comment]
Could you get the inserts done for that document throughout it's lifetime?

**Comment by Sigurs** [comment]
Here's an example:
@mkotb @erosemberg 
http://hastebin.com/uzifohoweh.sm
http://pastebin.com/kJLvfF3B
(same paste, hastebin just looks better if it's working)

Here's a example server.log http://pastebin.com/527xjgST

**Comment by exception** [comment]
Codewise, i dont see any reasons why this should be happening.

**Comment by ghost** [comment]
Yep, same problem. @mkotb 
First, the server starts... If the server has started, the port changed to something. Within a few seoncds the port is back to -1 but the ram usage and tps changed. After under a second, the server stops and start again, in an infinite loop.

Docker's status says, after excatly 30 seconds the server stops instantly. From docker it looks, the port only changes one time. So it don't go back to -1.

This is a bad idea maybe, but the server starts at my roots starts in 10seconds.
This is the code from the minecloud-bukkit plugin.

```

        new BukkitRunnable() {
            @Override
            public void run() {
                Server server = mongo.repositoryBy(Server.class).findFirst(serverId);
                Runtime runtime = Runtime.getRuntime();

                if (server == null) {
                    getLogger().info("Server removed from db, shutting down");
                    Bukkit.shutdown();
                    return;
                }

                server = server();

                server.setRamUsage((int) ((runtime.totalMemory() - runtime.freeMemory()) / 1048576));
                server.setTps(fetchTps());
                updatePlayers(server);

                mongo.repositoryBy(Server.class).save(server);

                //Heartbeat
                try (Jedis jedis = redis.grabResource()) {
                    jedis.hset("server:" + server.entityId(), "heartbeat", String.valueOf(System.currentTimeMillis()));
                }
            }
        }.runTaskTimerAsynchronously(this, 40, 200);
```

Is it difficult to say, but i think the port is either here overwritten or something else goes wrong.
