### ISSUE TITLE
xception in thread "Thread-4" java.lang.NullPointerException

### ISSUE THREAD

**Issue by eXAccept** [mkotb/MineCloud#30]
Jan 03, 2016 9:05:39 PM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFO: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "Thread-4" java.lang.NullPointerException
        at io.minecloud.daemon.StatisticsWatcher.run(StatisticsWatcher.java:130)

OS: Ubuntu 14.04
also i tried daemon.jar on debian-8-jessie and i got same error.

**Comment by mkotb** [comment]
You will need to add that node to the database. You can do that through the CLI.
