### ISSUE TITLE
Allow custom executor

### ISSUE THREAD

**Issue by csh** [mkotb/MineCloud#35]
Currently the way that a `RedisChannel` creates it's subscriber `Thread` conflicts with BungeeCord's `SecurityManager` impl. Not everyone has a `SecurityManager` free environment so it'd be nice to specify _how_ `RedisChannel` spawns the subscriber thread.

**Comment by ghost** [comment]
The redis operations should be only maked in a extra thread ( asnyc ). This will prevent the secruity from stopping the code and gives extra performance.

**Comment by csh** [comment]
Redis operations **should** be performed in another thread, I agree. You are missing the point though. Instantiation of a `RedisChannel` automatically spawns it's own thread which subscribes to the channel, it's nonsensical to potentially spawn another thread (assuming use of a `ThreadPoolExecutor` - what I believe backs the BungeeCord secheduler) for such a short lived task.

One should not have to rely on such tricks to make this usable. Spawning unnecessary threads does more damage than it does good and certainly doesn't lead to a performance increase.

**Comment by ghost** [comment]
Ohh, I am not familiar with Redis, because I do not need it at the moment.

**Comment by csh** [comment]
Closing this because we've added the necessary functionality to our fork.

**Comment by ghost** [comment]
Okay ;) I saw this already
