### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by katzendrama** [mkotb/MineCloud#38]
Hello i have problems to Compile MineCloud can you send me the jars?

**Comment by Valyrox** [comment]
If you don't manage to compile Minecloud, I doubt you get to make it work properly. It's hard when you don't know how it work. Just simply compile it with Maven (mvn clean package).

**Comment by katzendrama** [comment]
Okay and doest it works on an Windows Server?

**Comment by katzendrama** [comment]
Can you please Give me Instructions (i have Eclipse) how to Compile?

**Comment by mkotb** [comment]
MineCloud only works on Linux systems, sorry!
