### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by jimmyr57000** [mkotb/MineCloud#41]
Hello,
I have this problem : http://prnt.sc/efg4ny
its 4 hours that I do not find!
(I have created a database and a user, mongodb)

**Comment by jimmy57000** [comment]
Find: https://github.com/mkotb/MineCloud/wiki/Installation (Thanks)

I have another problem there is a lot of error ..

-> http://prntscr.com/efe8su
Another error: http://prntscr.com/efe93k :/

**Comment by Valyrox** [comment]
It's resolved? Your authentification id's are incorrect in the MineCloud configuration.. ^^

**Comment by jimmyr57000** [comment]
The problem comes from the method used in the plugin! (The developer solved the problem by removing the mongo user).

The system is no longer updated....

There is no documentation for setting up with cli.
Loss of time in real life.
